services:
  - type: web
    name: blog-laravel
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: redis
      - key: REDIS_CLIENT
        value: predis
      - key: REDIS_CACHE_DB
        value: "0"
      - key: REDIS_URL
        sync: false
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: fr
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
